### ISSUE TITLE
Go to line not working through keyboard shortcut on Mac

### ISSUE THREAD

**Issue by codemanmeet** [atom/go-to-line#30]
When I press <kbd>Control</kbd> + <kbd>G</kbd> the go to line minibar doesn't pop up on the first time. It pops up on the second time I press the keyboard shortcut. After that, when I enter the line number, instead going to that line, the cursor moves to the editor and that number is just typed in the editor. In the gif shown below, it can be seen that when I typed `4` in the line input bar, `4` just ended up in the first line of the editor screen where my cursor was before.

![atom-bug](https://cloud.githubusercontent.com/assets/4116346/13930567/468e0150-efda-11e5-9193-be324b520c91.gif)

**Comment by 50Wliu** [comment]
@codemanmeet Can you reproduce this in safe mode (`atom --safe`)?

**Comment by jyork779** [comment]
I'm getting the same issue.  I'm using Atom 1.6.2 and go-to-line 0.30.0.  After hitting ctrl+g it rarely comes up and when it does it will put the line number into the file instead of taking me to that line.  I'm new to Atom and like it.  Just need to know if there's a way around this issue.

**Comment by codemanmeet** [comment]
@50Wliu I'm using Atom v1.6.2. Works perfectly fine if I use `atom --safe`. But I face the same issue as described above when I use Atom in non-safe mode.

**Comment by 50Wliu** [comment]
In that case, one of the packages you're using is causing this issue.  You can try using the [package-cop](https://atom.io/package-cop) package by @mark-hahn to figure out exactly which package is breaking go-to-line.
