### ISSUE TITLE
Feature Request: automatically unfold sections containing target line

### ISSUE THREAD

**Issue by lzkelley** [atom/go-to-line#39]
It would be really cool if sections automatically unfolded when the `go-to-line` was inside them, instead of just being (vaguely) directed to the containing block.  At least a user option for it would be nice

**Comment by 50Wliu** [comment]
Luckily for you @lzkelley, this was actually implemented just a month ago!  This will happen automatically in Atom 1.13.0 (currently in beta) and above.
