### ISSUE TITLE
<unknown> is deprecated.

### ISSUE THREAD

**Issue by MateuszFlisikowski** [atom/go-to-line#45]
You have the core package "go-to-line" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.
```
<unknown> (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\dalek\lib\main.js:14:14)
Function.module.exports.Emitter.simpleDispatch (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
Emitter.emit (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:141:28)
<unknown> (C:\Users\mateusz\AppData\Local\atom\app-1.16.0\resources\app.asar\src\package-manager.js:514:32)
```

**Comment by rsese** [comment]
See the error message for details on how to resolve this problem:

> You have the core package "go-to-line" installed as a community package. See https://github.com/atom/dalek for how this causes problems and instructions on how to correct the situation.

In particular, see this section of the https://github.com/atom/dalek README for step-by-step instructions:

https://github.com/atom/dalek#i-got-a-warning-what-do-i-do

Let me know if you have any trouble with the process.
